export const useClockStyles = (hourDegree, minuteDegree, secondsDegree) => ({
    clockContainer: {
        position: 'relative',
        width: '200px',
        height: '200px',
        borderRadius: '50%',
        border: '1px solid black',
    },
    clockCenter: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        width: '10px',
        height: '10px',
        borderRadius: '50%',
        backgroundColor: 'black',
        transform: 'translate(-50%, -50%)',
    },
    hourHand: {
        position: 'absolute',
        bottom: '50%',
        left: '50%',
        width: '4px',
        height: '40%',
        backgroundColor: 'black',
        transformOrigin: 'bottom',
        transform: `translateX(-50%) rotate(${hourDegree}deg)`,
    },
    minuteHand: {
        position: 'absolute',
        bottom: '50%',
        left: '50%',
        width: '2px',
        height: '45%',
        backgroundColor: 'black',
        transformOrigin: 'bottom',
        transform: `translateX(-50%) rotate(${minuteDegree}deg)`,
    },
    secondsHand: {
        position: 'absolute',
        bottom: '50%',
        left: '50%',
        width: '1px',
        height: '50%',
        backgroundColor: 'red',
        transformOrigin: 'bottom',
        transform: `translateX(-50%) rotate(${secondsDegree}deg)`,
    },
});